# site
title: cam carter
baseurl: ""
url: "https://cam-carter.github.io"
favicon: "/assets/images/ico.png"
g_analytics: UA-12345678-1

# bio
header: Cam Carter
desc: >
  Hello world! Welcome to my corner of the internet.
  (or is the internet round?)

# posts
date_format: "%-d %B %Y"
# post_title: Title
# post_date: Date

# post detail
prev-next: false

# build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
